cobalt/demos/content/media-element-demo/package-lock.json
Reverts youtube/cobalt_sandbox#13
=> Revert "Delete media-demos/package.log"

.github/workflows/evergreen_23.lts.1+.yaml, .github/workflows/main.yaml
* Fix evergreen workflow names.
* Don't build linux boot loader for debug, gold, and qa variants.
=> Cleanup 23.lts.1+ workflows.

.github/workflows/main.yaml
This makes job name consistent with other jobs.
=> Change on device job name.

third_party/jinja2/filters.py
Unicode matching is the default with python 3.
=> Remove obsolete and deprecated re.UNICODE flag

.github/actions/on_device_tests/action.yaml, .github/config/android-arm.json, .github/config/android-arm64.json, .github/config/android-x86.json, .github/config/raspi-2.json, .github/workflows/main.yaml, tools/on_device_tests_gateway.proto, tools/on_device_tests_gateway_client.py
=> Setup ODT sharding

.github/workflows/main.yaml
This is required to have new image pushed to GHR.
=> Grant package:write permission for UT image build

.github/actions/on_device_tests/action.yaml
=> Add dimension arg to MH action.

.github/config/evergreen-arm-hardfp.json, .github/config/raspi-2.json
=> Disable integration tests on raspi-2 platforms.

.github/config/evergreen-arm-hardfp.json
=> Enable on-device tests on evergreen-arm-hardfp (23.lts.1+)

.github/config/raspi-2.json, starboard/tools/testing/test_runner.py
=> Succeed when FLAKY tests are de-flaked

.github/workflows/main.yaml
=> (23.lts.1+) Pass includes.target_platform to ODT.

.github/config/raspi-2-skia.json, .github/config/raspi-2.json, .github/workflows/raspi-2.yaml
This will allow to easily disable on-device-test
for raspi-2-skia.
b/267496346
=> Separate raspi-2-skia from raspi-2 config.

.github/workflows/pr_badges.yaml
This PR addresses security vulnerabilities by:
* Stop passing GITHUB_SECRET explicitly.
* Avoid code and command injection vulnerabilities by setting the untrusted input value of the expression to an intermediate environment variable (see Remediation Guidance in b/267705413).
b/267705413
=> Address security vulnerability in pr_badges workflow.

.github/config/raspi-2-skia.json, .github/config/raspi-2.json, .github/workflows/raspi-2_23.lts.1+.yaml
Disables on-device-test on raspi-2-skia.
b/267496346
=> (23.lts.1+) Separate raspi-2-skia from raspi-2 config. (#215)

.github/workflows/main.yaml
=> (22.lts.1+) Pass includes.target_platform to ODT.

.github/workflows/main.yaml
=> (21.lts.1+) Pass includes.target_platform to ODT.

.github/actions/gn/action.yaml, .github/config/evergreen-arm-hardfp.json
'bootloader' and 'dimension' parameters have been added
b/268365629
=> (23.lts.1+) Add missing configs to evergreen-arm-hardfp

tools/on_device_tests_gateway_client.py
Setting change didn't fix the problem.
=> Revert "Adjust keepalive settings in ODT client."

starboard/win/win32/test_filters.py
b/256160416
Change-Id: I0c924be8f403169a4437fc8871e990a358096125 NOKEYCHECK=True
GitOrigin-RevId: 38d72a545ec1b8caef51472bd279b2149b4fa0bf
=> [win32] Disable failing nplb tests

.github/config/raspi-2.json
=> (23.lts.1+) Disable integration tests on raspi-2 platforms.

.github/workflows/android_23.lts.1+.yaml, .github/workflows/evergreen_23.lts.1+.yaml, .github/workflows/linux_23.lts.1+.yaml, .github/workflows/main.yaml, .github/workflows/main_win.yaml, .github/workflows/raspi-2_23.lts.1+.yaml, .github/workflows/stub_23.lts.1+.yaml, .github/workflows/win32_23.lts.1+.yaml
=> (23.lts.1+) Fix label based workflow trigger.

.github/workflows/android_22.lts.1+.yaml, .github/workflows/evergreen_22.lts.1+.yaml, .github/workflows/linux_22.lts.1+.yaml, .github/workflows/main.yaml, .github/workflows/raspi-2_22.lts.1+.yaml
=> (22.lts.1+) Fix label based workflow trigger.

.github/workflows/evergreen_21.lts.1+.yaml, .github/workflows/linux_21.lts.1+.yaml, .github/workflows/main.yaml, .github/workflows/raspi-2_21.lts.1+.yaml
=> (21.lts.1+) Fix label based workflow trigger.

.github/workflows/linux_19.lts.1+.yaml, .github/workflows/main.yaml, .github/workflows/raspi-2_19.lts.1+.yaml
=> (19.lts.1+) Fix label based workflow trigger.

.github/workflows/main.yaml
Set github context variables in env vars.
b/268072581
=> Address command injection vulnerability.

.github/workflows/main_win.yaml, .github/workflows/win32.yaml
=> Remove 'runtest' label in win worklows.

.github/workflows/main.yaml
=> Fix 'on_device' label trigger.

.github/workflows/main.yaml
=> Pass correct bootloader config to Evergreen ODT

.github/workflows/main_win.yaml
=> (23.lts.1+) Address command injection vulnerability.

.github/workflows/main.yaml
=> (22.lts.1+) Fix 'on_device' label workflow trigger.

tools/create_archive.py
=> Fix more packaging in create_archive

.github/actions/on_host_test/action.yaml
=> Remove deprecated evergreen_tests flag

.github/actions/upload_test_artifacts/action.yaml, .github/workflows/main.yaml
=> Fix missing bootloader dir in ODT archive.

.github/workflows/android.yaml, .github/workflows/evergreen.yaml, .github/workflows/lint.yaml, .github/workflows/linux.yaml, .github/workflows/pr_badges.yaml, .github/workflows/raspi-2.yaml, .github/workflows/stub.yaml, .github/workflows/win32.yaml
=> Enable workflows on feature branches.

.github/actions/docker/action.yaml, .github/actions/docker_win/action.yaml, .github/workflows/main.yaml, .github/workflows/main_win.yaml, .github/workflows/scorecards.yml
=> Pin third party actions.

.github/actions/docker/action.yaml, .github/workflows/main.yaml
=> (COBALT_9) Pin third party actions. (#295)

.github/actions/docker/action.yaml, .github/workflows/main.yaml
=> (rc_11) Pin third party actions. (#295)

.github/actions/docker/action.yaml, .github/workflows/main.yaml
=> (19.lts.1+) Pin third party actions. (#295)

.github/actions/docker/action.yaml, .github/workflows/main.yaml
=> (20.lts.1+) Pin third party actions. (#295)

.github/actions/docker/action.yaml, .github/workflows/main.yaml
=> (21.lts.1+) Pin third party actions. (#295)

.github/actions/docker/action.yaml, .github/workflows/main.yaml
=> (22.lts.1+) Pin third party actions. (#295)

.github/actions/docker/action.yaml, .github/actions/docker_win/action.yaml, .github/workflows/main.yaml, .github/workflows/main_win.yaml
=> (23.lts.1+) Pin third party actions. (#295)

.github/actions/on_host_test/action.yaml, .github/actions/upload_test_artifacts/action.yaml, .github/workflows/main.yaml, .github/workflows/main_win.yaml
New sccache, build, and test artifact buckets.
b/272578336
=> Reconfigure workflows to point to new buckets

.github/workflows/manual-cherry-pick.yaml
=> Use bot PAT to create cherry pick PRs

.github/workflows/manual-cherry-pick.yaml
=> Set reviewer for CPs as triggering user

cobalt/webdriver/algorithms.cc, cobalt/webdriver/algorithms.h, cobalt/webdriver/dispatcher.h, cobalt/webdriver/element_driver.cc, cobalt/webdriver/element_driver.h, cobalt/webdriver/protocol/button.h, cobalt/webdriver/protocol/capabilities.h, cobalt/webdriver/protocol/cookie.h, cobalt/webdriver/protocol/element_id.h, cobalt/webdriver/protocol/frame_id.h, cobalt/webdriver/protocol/log_entry.cc, cobalt/webdriver/protocol/log_entry.h, cobalt/webdriver/protocol/moveto.h, cobalt/webdriver/protocol/response.h, cobalt/webdriver/protocol/script.h, cobalt/webdriver/protocol/server_status.h, cobalt/webdriver/protocol/session_id.h, cobalt/webdriver/server.cc, cobalt/webdriver/server.h, cobalt/webdriver/web_driver_module.cc, cobalt/webdriver/window_driver.cc
This updates webdriver links to their new locations, with versioning.
b/200993308
=> Fix webdriver links.

sandbox/nyardi.txt
=> nyardi: commit one

starboard/media.h
This is a test commit.
b/276483058
=> [media] Refine comment of media.h

sandbox/yijiazhang.txt
follow setup guide
b/277642525
=> yijiazhang's first commit

.github/workflows/test-report.yaml
=> Add workflow step that creates a unit test report

.github/workflows/label-cherry-pick.yaml
=> Add label based cherry pick workflow

.github/workflows/android.yaml, .github/workflows/main.yaml
Reverts youtube/cobalt_sandbox#390
=> Revert "Test fix nightly trigger"

.github/workflows/android.yaml
Reverts youtube/cobalt_sandbox#391
=> Revert "Revert "Test fix nightly trigger""

.github/workflows/android.yaml
Reverts youtube/cobalt_sandbox#393
=> Revert "Revert "Revert "Test fix nightly trigger"""

third_party/derp/derp.txt
=> Add subtree third_party/derp.

third_party/derp/derpo.txt
Update subtree third_party/derp.
=> Update subtree third_party/derp.

README.md
=> Hopefully final email test

README.md
=> Testing buganizer

README.md
b/1234
Change-Id: I4715c52bfaa6b3ae3968f38d5d6cabfd143cccdd
NOKEYCHECK=True
GitOrigin-RevId: 609653c28f398e3dd9b03580635c64966a215ca9
=> Test copybara continuously

.github/workflows/scorecards.yml
Scorecards are getting errors, trying an update to see if this resolves it.
=> Update ossf scorecards version to latest

.github/workflows/unit_test_report.yaml
=> Fix array indexing, more logging

.github/workflows/unit_test_report.yaml
=> Upload improvements

.github/workflows/lint.yaml
=> Check PR for bug number

.github/workflows/unit_test_report.yaml
=> Add comment on PR step

.github/workflows/unit_test_report.yaml
=> Final clean up

.github/workflows/label-cherry-pick.yaml
=> Add title to cherry picked PRs

.github/workflows/label-cherry-pick.yaml
=> Use body in CP PR message

test_file
Cherry picking this PR should fail with a merge conflict
=> Add test file

build/toolchain/concurrent_links.gni, docker-compose-windows.yml
Apply changes from main repo to concurrent_links.gni
Change to win64 based build
b/266878119
=> Attempt to get xb1 builders working

.github/workflows/android.yaml
Uploads Android APK bundle to releases.
b/318577880
b/290121545
=> Add Android release artifacts on release

.github/workflows/workflow_trigger.yaml
=> Add 25.lts

.github/actions/docker/action.yaml, .github/actions/docker_win/action.yaml
Old changed-files breaks with Release events
b/318577880
=> Upgrade changed-files action

docker/linux/base/Dockerfile, docker/linux/base/build/Dockerfile
=> Cache busting docker tags

.github/actions/on_device_tests/action.yaml, .github/workflows/unit_test_report.yaml, tools/on_device_tests_gateway.proto, tools/on_device_tests_gateway_client.py
This way the plugin can upload multiple files to the destination without
path manipulation.
=> Upload ODT test results to GCS

.github/workflows/main.yaml
Tries to run `journalctl` and fails. Looks like all build jobs are broken.
Reverts youtube/cobalt_sandbox#690
=> Revert "test action"

docker-compose.yaml
Reverts youtube/cobalt_sandbox#719
=> Revert "test rbe"

.github/config/android-arm.json, .github/config/android-arm64.json, .github/config/android-x86.json, .github/config/chromium_android-arm.json, .github/config/chromium_android-arm64.json, .github/config/chromium_android-x86.json, .github/config/chromium_linux.json, .github/config/linux.json, .github/workflows/main.yaml, docker-compose.yaml
=> Break out test targets into a separate config

.github/workflows/sync_chromium_branches.yaml
Change-Id: Ieb977a9869fb491f4e746e2628933767998efda0
=> Add test workflow to automate rebasing.

.github/workflows/sync_chromium_branches.yaml
Change-Id: Ia5b7e2ca3adddc7e1bb7037e06353a584aa13adf
=> Fix syntax error for rebase commit

.github/workflows/sync_chromium_branches.yaml
Change-Id: I82018cf3db0e0abc7fd82f5aa2c127a06a9b14af
=> fix target to use milestone rather than branch

.github/workflows/sync_chromium_branches.yaml
Change-Id: I985412293256008e9cc92e1d9e03873c435e0c80
=> Add token for auth

.github/workflows/sync_chromium_branches.yaml
Change-Id: I1bd61d09e3322f666d96e8cb037f2b9f234e5ceb
=> Add username and email for auth

.github/workflows/sync_chromium_branches.yaml
Change-Id: Idb3dbd5750b3f5c90fd0b09f5f6d5951d50fe828
=> Add check for diffs

.github/workflows/sync_chromium_branches.yaml
Change-Id: I2c82676e54ea6454e7a89f178c3a7be7371cf8fe
=> Re-adding logging messages

.github/workflows/sync_chromium_branches.yaml
Change-Id: I2f7eb2708f989de171fd17f1e45acb147d856a1e
=> Add step to free space on the GitHub runner

.github/workflows/sync_chromium_branches.yaml
Change-Id: I6edf21aa989cb216e1847b394d86ff54cc43ea28
=> Add measuring for volumes

.github/workflows/sync_chromium_branches.yaml
correctly being checked by GHA.
Change-Id: I9c3421f53cf405fe0e1d10d0062320638839f2d8
=> Removed unnecessary logging and added log to check if the diff patch is

.github/workflows/sync_chromium_branches.yaml
Change-Id: I568c4829ffdbef6f8e984a820dbf438a4cd6b4d1
=> Testing new branch rebasing feature to add brand new milestones
