youtube/cobalt_sandbox

.github/workflows/evergreen_23.lts.1+.yaml

The workflow was missing branch name for pull_request trigger.

Fix evergreen_23.lts.1+ workflow.

---

starboard/win/shared/BUILD.gn

This does not break win32 builds and is in cobalt_src.

Replace conditional for uwp builds

---

cobalt/black_box_tests/tests/deep_links.py

Reset the synchronization event for every test invocation. It would be better to not declare it at module level at all and move it to test class scope, but this should keep the fix simpler.
b/232938389

Fix deeplink test sync issue

---

.github/workflows/main.yaml

This fixes the problem where GitHub throws "Error: Unable to process file command 'env' successfully." error when MH invocation fails.
b/267508341

Extract session id before writing it to GITHUB_ENV (21.lts.1+)

---

.github/workflows/main.yaml

This fixes the problem where GitHub throws "Error: Unable to process file command 'env' successfully." error when MH invocation fails.
b/267508341

Extract session id before writing it to GITHUB_ENV (22.lts.1+)

---

.github/workflows/main.yaml

This fixes the problem where GitHub throws "Error: Unable to process file command 'env' successfully." error when MH invocation fails.
b/267508341

Extract session id before writing it to GITHUB_ENV (23.lts.1+).

---

cobalt/base/deep_link_event.h
cobalt/h5vcc/h5vcc_runtime.cc
cobalt/h5vcc/h5vcc_runtime.h

This ensures ordering of stashed deep links in H5vccRuntime by ensuring it's only done from the thread that instantiated the object.
b/263967861
Change-Id: I3e200cda6ba79afa205e5bcbe81c2dc13cb87c94

Ensure ordering of stashed deep links.

---

tools/on_device_tests_gateway_client.py

Increase time between pings to 30 seconds.
Increase keepalive timeout to 15 seconds.
b/267656691

Adjust keepalive settings in ODT client.

---

.github/actions/upload_nightly_artifacts/action.yaml
.github/actions/upload_test_artifacts/action.yaml

gsutil appears to be twice as fast as google-github-actions/upload-cloud-storage. We also use gsutil to download artifacts and it never fails.  Switching to gsutil with -d option should also help us with debug output printed to logs.
b/266771047

Use gsutil to upload test archives.

---

starboard/tools/testing/test_runner.py

* Succeed when FLAKY tests are de-flaked
b/263397348
This reverts commit 0734b375d1aaecd4605e5532d4f0cb57da74348a.
(cherry picked from commit 4eef4140bdf076aedb478d25b233bc798d51eb2a)

Succeed when FLAKY tests are de-flaked (#211)

---

.github/actions/upload_nightly_artifacts/action.yaml
.github/actions/upload_test_artifacts/action.yaml

(23.lts.1+) Use gsutil to upload test archives. (#230)

---

.github/actions/upload_nightly_artifacts/action.yaml
.github/actions/upload_test_artifacts/action.yaml

(22.lts.1+) Use gsutil to upload test archives. (#230)

---

.github/actions/upload_nightly_artifacts/action.yaml
.github/actions/upload_test_artifacts/action.yaml

(20.lts.1+) Use gsutil to upload test archives. (#230)

---

.github/actions/upload_nightly_artifacts/action.yaml
.github/actions/upload_test_artifacts/action.yaml

(19.lts.1+) Use gsutil to upload test archives. (#230)

---

.github/actions/upload_nightly_artifacts/action.yaml
.github/actions/upload_test_artifacts/action.yaml

(rc_11) Use gsutil to upload test archives. (#230)

---

.github/actions/upload_nightly_artifacts/action.yaml
.github/actions/upload_test_artifacts/action.yaml

(COBALT_9) Use gsutil to upload test archives. (#230)

---

cobalt/base/deep_link_event.h
cobalt/h5vcc/h5vcc_runtime.cc
cobalt/h5vcc/h5vcc_runtime.h

This ensures ordering of stashed deep links in H5vccRuntime by ensuring it's only done from the thread that instantiated the object.
b/263967861
Change-Id: I3e200cda6ba79afa205e5bcbe81c2dc13cb87c94
Co-authored-by: Jelle Foks <jfoks@google.com>

Ensure ordering of stashed deep links. (#212)

---

.github/actions/docker_win/action.yaml

Latest Windows 2019 GitHub runner image had docker engine upgraded from 20.10.23 to 23.0.1.  This caused incompatiblity with Docker Compose v1 which has been deprecated.  As of right now, there is no way to use Docker Compose v2 with smartlyio/docker-compose-action (see https://github.com/smartlyio/docker-compose-action/issues/567).
b/269780709

Use docker compose v2 to build win docker images

---

.github/workflows/lint.yaml

Commit message workflow will contain all checks related to commit messages.  For now it checks for a bug ID only.
Expand linting and bug id check to legacy branches, and explicitly list types for triggers.
b/263984710

Add bug id check job to lint workflow

---

.github/workflows/main.yaml

MH infra for 22.lts.1+ and older branches expects variant name (e.g. 'sbersion-12') as part of --platform parameter value.
b/271325762

Pass correct platform parameter to ODT

---

.github/workflows/main.yaml

MH infra for 22.lts.1+ and older branches expects variant name (e.g. 'sbersion-12') as part of --platform parameter value.
b/271325762

(21.lts.1+) Pass correct platform parameter to ODT (#290)

---

.github/config/evergreen-arm-hardfp.json

We don't run these tests on Buildbot.

Remove evergreen test from arm-hardfp ODT.

---

.github/actions/docker_win/action.yaml

Latest Windows 2019 GitHub runner image had docker engine upgraded from 20.10.23 to 23.0.1.  This caused incompatiblity with Docker Compose v1 which has been deprecated.  As of right now, there is no way to use Docker Compose v2 with smartlyio/docker-compose-action (see https://github.com/smartlyio/docker-compose-action/issues/567).
b/269780709

(23.lts.1+) Use docker compose v2 to build win docker images (#281)

---

.github/workflows/lint.yaml
.github/workflows/main.yaml
.github/workflows/main_win.yaml
.github/workflows/pr_badges.yaml

Change concurrency setting to make sure workflows of different event types (e.g. pull_request, push, workflow_dispatch) do not cancel each other.

Tune GitHub workflow concurrency

---

.github/workflows/main.yaml

Introduce RUN_ODT_TESTS_ON_NIGHTLY and
RUN_ODT_TESTS_ON_POSTSUBMIT repo variables.
b/278898541

Use repo vars to control ODT execution.

---

.github/actions/docker/action.yaml

As of right now, there is no way to use
Docker Compose v2 with smartlyio/docker-compose-action. Docker Compose v1 has been deprecated and use of v1 is causing compatability issues with ARC infra.
b/280495066
b/278624932

Stop using smartlyio/docker-compose-action

---

.github/actions/docker/action.yaml

As of right now, there is no way to use
Docker Compose v2 with smartlyio/docker-compose-action. Docker Compose v1 has been deprecated and use of v1 is causing compatability issues with ARC infra.
b/280495066
b/278624932

Stop using smartlyio/docker-compose-action (#396)

---

.github/workflows/unit_test_report.yaml

Clean up datadog upload workflow

---

.github/workflows/unit_test_report.yaml

Fix syntax error

---

.github/actions/on_host_test/action.yaml
.github/workflows/coverage.yaml
.github/workflows/linux.yaml
.github/workflows/main.yaml
starboard/tools/testing/test_runner.py

The coverage job does not support sharding and takes ~1h to run. That's
~40 minutes longer than all other linux test runs. By breaking out
coverage from the linux workflow we can get unit test results from
datadog in less than half the time.
b/290997541

Move coverage to its own workflow (#1063)

---

.github/workflows/label-cherry-pick.yaml

Comment on cherry pick PR on failure
